In [1]:
from ipumspy import readers
import pandas as pd

In [2]:
ddi1 = readers.read_ipums_ddi("usa_00011.xml")
df1  = readers.read_microdata(ddi1, "usa_00011.dat.gz")

df1.head()

/opt/anaconda3/lib/python3.13/site-packages/ipumspy/readers.py:70: CitationWarning: Use of data from IPUMS is subject to conditions including that users should cite the data appropriately.
See the `ipums_conditions` attribute of this codebook for terms of use.
See the `ipums_citation` attribute of this codebook for the appropriate citation.
  warnings.warn(

,YEAR,STATEFIP,PERWT,SEX,AGE,RACE,RACED,HISPAN,HISPAND,EDUC,EDUCD,DEGFIELD,DEGFIELDD,EMPSTAT,EMPSTATD,WKSWORK1,UHRSWORK,INCWAGE
0,2010,1,96.0,2,75,1,100,0,0,6,63,0,0,3,30,<NA>,0,0
1,2010,1,97.0,1,25,1,100,0,0,11,114,50,5007,1,10,<NA>,20,17000
2,2010,1,128.0,2,26,1,100,0,0,7,71,0,0,1,10,<NA>,20,13000
3,2010,1,182.0,1,3,1,100,0,0,0,2,0,0,0,0,<NA>,0,999999
4,2010,1,90.0,2,87,1,100,0,0,7,71,0,0,3,30,<NA>,0,0

In [3]:
ddi2 = readers.read_ipums_ddi("usa_00012.xml")
df2  = readers.read_microdata(ddi2, "usa_00012.dat.gz")

df2.head()

/opt/anaconda3/lib/python3.13/site-packages/ipumspy/readers.py:70: CitationWarning: Use of data from IPUMS is subject to conditions including that users should cite the data appropriately.
See the `ipums_conditions` attribute of this codebook for terms of use.
See the `ipums_citation` attribute of this codebook for the appropriate citation.
  warnings.warn(

,YEAR,STATEFIP,PERWT,SEX,AGE,RACE,RACED,HISPAN,HISPAND,EDUC,EDUCD,DEGFIELD,DEGFIELDD,EMPSTAT,EMPSTATD,WKSWORK1,UHRSWORK,INCWAGE
0,1950,23,37.0,1,36,1,100,0,0,0,0,<NA>,<NA>,1,10,0,<NA>,999999
1,1950,23,37.0,2,36,1,100,0,0,2,25,<NA>,<NA>,3,31,0,<NA>,0
2,1950,23,37.0,1,14,1,100,0,0,0,0,<NA>,<NA>,3,34,0,<NA>,999999
3,1950,23,37.0,2,12,1,100,0,0,0,0,<NA>,<NA>,0,0,0,<NA>,999999
4,1950,23,37.0,2,10,1,100,0,0,0,0,<NA>,<NA>,0,0,0,<NA>,999999

In [4]:
df3 = pd.concat([df2, df1], ignore_index = True)

In [5]:
df3.to_parquet("acs.parquet", index=False)

In [6]:
df3.head()

,YEAR,STATEFIP,PERWT,SEX,AGE,RACE,RACED,HISPAN,HISPAND,EDUC,EDUCD,DEGFIELD,DEGFIELDD,EMPSTAT,EMPSTATD,WKSWORK1,UHRSWORK,INCWAGE
0,1950,23,37.0,1,36,1,100,0,0,0,0,<NA>,<NA>,1,10,0,<NA>,999999
1,1950,23,37.0,2,36,1,100,0,0,2,25,<NA>,<NA>,3,31,0,<NA>,0
2,1950,23,37.0,1,14,1,100,0,0,0,0,<NA>,<NA>,3,34,0,<NA>,999999
3,1950,23,37.0,2,12,1,100,0,0,0,0,<NA>,<NA>,0,0,0,<NA>,999999
4,1950,23,37.0,2,10,1,100,0,0,0,0,<NA>,<NA>,0,0,0,<NA>,999999